language: node_js
node_js:
- "7"

script: npm run build

deploy:
  fqdn: esquinas.github.io/que-jamon-elegir
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
